tests: tests.cpp primitives.cpp primitives_utils.cpp contraction_record.cpp
	g++ -Wall tests.cpp primitives.cpp primitives_utils.cpp contraction_record.cpp -o tests.exe -IC:\Users\luchn\dev\boost_1_78_0
	./tests.exe